### ISSUE TITLE
Allow closures in Server::new

### ISSUE THREAD

**Issue by Kixunil** [steveklabnik/simple-server#101]
`Server::new` currently accepts only fn pointer, so if one wants to access a variable, it must be static.

Accepting closures would resolve this problem.

**Comment by steveklabnik** [comment]
This is solved on master: https://github.com/steveklabnik/simple-server/blob/master/src/lib.rs#L57

**Comment by Kixunil** [comment]
Nice, thanks! I'll try to point cargo at the repo directly for now.
