### ISSUE TITLE
body() sometimes returns zeroed slice

### ISSUE THREAD

**Issue by Kixunil** [steveklabnik/simple-server#102]
In the handler I have `eprintln!("{:?}", request.body())`. The client sending the request is Chrome using AJAX. I have a button on the page which sends JSON when one clicks it. If I try to click it few times in a row, one of the requests prints out zeroed slice of different length, the rest are correct. I've checked with Wireshark and the request seems correct, so the issue is in `simple-server`.

**Comment by steveklabnik** [comment]
Hm, this is very odd. After I merge https://github.com/steveklabnik/simple-server/pull/104 I'll try to reproduce.

**Comment by Kixunil** [comment]
I've switched to master. Now instead of zeroes, it returns empty slice.

**Comment by steveklabnik** [comment]
Idea: is it CORS?

**Comment by Kixunil** [comment]
No. Even if it was, I don't see how it could be related, since the browser sends the same request every time.

**Comment by steveklabnik** [comment]
I cannot reproduce this. Cargo is pointed to current `HEAD`.

`src/main.rs`:

```
extern crate simple_server;

use simple_server::Server;

fn main() {
    let host = "127.0.0.1";
    let port = "7878";

    let server = Server::new(|request, mut response| {
        eprintln!("{:?}", request.body());
        Ok(response.body("Hello Rust!".as_bytes().to_vec())?)
    });

    server.listen(host, port);
}
```

`public/foo.html`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>A static page</title>
  </head>
  <body>
      
<button onclick="post()">push me</button>

<script>
function post() {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        alert("success");
    }
  };
  xhttp.open("POST", "/post", true);
  xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  xhttp.send("name=testing"); 
  xhttp.send();
}
</script>

  </body>
</html>
```

output:

```bash
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\ss102.exe`
[110, 97, 109, 101, 61, 116, 101, 115, 116, 105, 110, 103]
[110, 97, 109, 101, 61, 116, 101, 115, 116, 105, 110, 103]
```

first push is firefox, second is chrome.

Does this demo work for you? What's different from what I'm doing from what you're doing?

**Comment by Kixunil** [comment]
Not on my computer now, so I'll try it later. Did you try multiple requests in a row? (clicking on the button multiple times) I noticed I encounter the issue in approximately 20% cases (1 of 5 attempts).

**Comment by steveklabnik** [comment]
I just did it 20 times in a row, printed out every time.

I *do* get an empty slice on the initial page load, that is, if i click refresh, since it's not a POST request, it has an empty body. Is that maybe it?

**Comment by Kixunil** [comment]
Weird, I can't reproduce it anymore with your example nor my own code. I think I might have had the `eprintln!` too soon and got confused and moved it into the match arm later.

I'm closing this and I'll reopen if I encounter it again.

Thank you and sorry for bothering you with false report.

**Comment by steveklabnik** [comment]
No worries! I'm just glad it's working. I'd always prefer more bug reports
than less.

I'm planning on cutting a release today or tomorrow, so you'll be able to
use 0.4 and not git HEAD. :)
