### ISSUE TITLE
When serving static files, they always must be in `public` directory.

### ISSUE THREAD

**Issue by Kixunil** [steveklabnik/simple-server#105]
Even if I set directory to e.g. `/var/www`, according to the code it searches in `/var/www/public`. Is this intentional? Shouldn't setting the directory overwrite `public` part too?

**Comment by steveklabnik** [comment]
It's not so much intentional as it is "that was my use-case and so i wrote it up that way."

I agree that requiring a certain path isn't the best though. We should probably change that before cutting the next release.
