### ISSUE TITLE
would be nice to remove `as_bytes`

### ISSUE THREAD

**Issue by ashleygwilliams** [steveklabnik/simple-server#2]
from #1 

`*response.body_mut() = "Hello Rust!".as_bytes();`

**Comment by steveklabnik** [comment]
The only real way to fix this is related to https://github.com/steveklabnik/simple-server/issues/3; this would require a change to `body_mut`'s interface.

**Comment by seanmonstar** [comment]
`b"Hello Rust!"` should give you a byte slice instead of a `str`.

**Comment by steveklabnik** [comment]
@seanmonstar it doesn't give a slice, it gives an array.

**Comment by steveklabnik** [comment]
This issue seems to be irrelevant today; this code no longer exists in our codebase. Thanks all!
