### ISSUE TITLE
make number of Pools configurable

### ISSUE THREAD

**Issue by ashleygwilliams** [steveklabnik/simple-server#27]
currently hardcoded at 4. https://github.com/steveklabnik/simple-server/blob/4f6050ad6b45caea93ff3caf31eaabfcd75174c3/src/lib.rs#L84

not urgent but nice to have

**Comment by gsquire** [comment]
Might it be beneficial to use the [num_cpus](https://crates.io/crates/num_cpus) crate? If so I can send a PR.
