### ISSUE TITLE
would be nice to remove `*`

### ISSUE THREAD

**Issue by ashleygwilliams** [steveklabnik/simple-server#3]
from #1 

```rust
*response.body_mut() = "Hello Rust!".as_bytes();
```

**Comment by steveklabnik** [comment]
This is a limitation of http's interface; it could be a 

    response.set_body("Hello Rust!".as_bytes());

instead. This is a style thing in Rust APIs; you'll see both, so whatever.

**Comment by steveklabnik** [comment]
This is fixed by the new builder.
