### ISSUE TITLE
take handler as a closure not a function

### ISSUE THREAD

**Issue by ashleygwilliams** [steveklabnik/simple-server#4]
from #1

```
    fn handler(request: Request<&[u8]>, response: &mut Response<&[u8]>) {
      println!("Request received. {} {}", request.method(), request.uri());
      *response.body_mut() = "Hello Rust!".as_bytes();
    };
```

**Comment by Michael-F-Bryan** [comment]
Restricting the server to only take a bare function feels really... odd. I was going to make an issue about it but looks like @ashleygwilliams has beaten me to it.

My thoughts were that you could always use some `Handler` trait (implemented by all immutable closures) and make the server generic over any handler, that way the lifetime issues are "hidden" by the `H: Handler` trait bound ([playground]).

Something like that is pretty standard in Rust. Although that may be contradicting the "simple" in `simple-server`...

[playground]: https://play.rust-lang.org/?gist=62887ef026808be7ed2177784c87a7b0&version=stable

**Comment by steveklabnik** [comment]
Yeah, so, the real question is, what is the use-case for using a closure here?

**Comment by Michael-F-Bryan** [comment]
Hmm... to make simple applications (i.e. the `Hello World` example) simple to write? Once you throw in more advanced things like routing or a database connection pool it's usually easier to wrap all that state and configuration up in its own type.

Do people typically use NodeJS's `createServer` for non-trivial applications involving routing and state?

**Comment by steveklabnik** [comment]
So, just ran into this! I had a feeling that we'd need to, but wanted to make absolutely sure.

**Comment by TheZoq2** [comment]
How difficult would it be to change this to accept a capturing closure instead of just a `fn` function pointer?

I have a use case where I have one thread dumping data into an `Arc<Mutex<Vec<String>>>` which I want to send to clients using http.

The simplest way I can come up with that would allow me to do this is 
```rust
let arc = //shared by multiple threads
Server::new(|request, mut response| {
    Ok(response.body(arc.lock().unwrap().as_bytes())
}
```

But because I can not pass it a closure, I cant do this.

**Comment by steveklabnik** [comment]
We actually implemented this!
https://github.com/steveklabnik/simple-server/pull/82

**Comment by TheZoq2** [comment]
Yep, I noticed that shortly after sending that message. Thanks
