### ISSUE TITLE
crates.io isn't using docs.rs fallback

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/simple-server#59]
This may be because the crate is new and there aren't docs there yet. It may be because that's broken or I misunderstood somehow. Investigation needed.

**Comment by ashleygwilliams** [comment]
looks like it was just a lag. closing.
<img width="433" alt="screen shot 2017-10-19 at 10 32 52 am" src="https://user-images.githubusercontent.com/1163554/31776287-17bf4046-b4b9-11e7-89d1-e7cf009d2eca.png">
