### ISSUE TITLE
Response headers are not written

### ISSUE THREAD

**Issue by divarvel** [steveklabnik/simple-server#71]
In this small example (<https://gist.github.com/divarvel/4c59b15d6921f79884b7638905faa4e9>) we can see that headers are not written in the answer (the `Location` header is missing). 

Indeed, `write_response` does not seem to include them
https://github.com/steveklabnik/simple-server/blob/master/src/lib.rs#L189

**Comment by divarvel** [comment]
FWIW https://github.com/divarvel/simple-server/tree/issues/71
It doesn't handle empty headers maps correctly and the code is ugly, but that's a start

**Comment by ashleygwilliams** [comment]
hey @divarvel ! thanks for filing, we may have some comments on the PR but it will be easiest to make them there, so please open one and we can chat! appreciate your work on this ✨

**Comment by divarvel** [comment]
Here it is https://github.com/steveklabnik/simple-server/pull/75

**Comment by ashleygwilliams** [comment]
closed with #75
