### ISSUE TITLE
Can't use owned bytes for body in Server handler?

### ISSUE THREAD

**Issue by kardeiz** [steveklabnik/simple-server#72]
It seems like you can't use owned data (e.g., `String` or `Vec<u8>`) for the response body in the `Server` handler. 

Unless I am missing something, this seems like a huge limitation: it prevents you from doing anything with the request data (at least easily).

It seems like you could use `Cow<'static, [u8]>` for the response body, or `Bytes`.

Am I missing something?

**Comment by kardeiz** [comment]
To clarify, I mean for example a `String` that is created within the handler `fn`.

**Comment by ashleygwilliams** [comment]
hi @kardeiz ! would it be possible for you to make a simple example of the functionality you'd want? AFAICT, it sounds reasonable. we're doing an interface driven approach, so if you provide an example of the interface you'd like we can evaluate it and then improve the API from there!

thanks for filing :)
