### ISSUE TITLE
Move from `fn` to `Fn`

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/simple-server#81]
We originally used `fn` because there was no need, but building more complex stuff needs `Fn`; for example, a framework writing their own `listen` method will want to use stuff from `self` inside of the server, but you can't create that stuff inside the `fn` passed to `new`.

**Comment by ashleygwilliams** [comment]
let's just use https://doc.rust-lang.org/std/ops/trait.Fn.html

**Comment by steveklabnik** [comment]
yeah, i miss-spoke 👍
