### ISSUE TITLE
request method not used when matching routes

### ISSUE THREAD

**Issue by kardeiz** [steveklabnik/simple-server#83]
For example, the `routes` example exhibits incorrect behavior:

    curl -X POST localhost:7878/hello

returns

    <h1>Hi!</h1><p>Hello Rust!</p>

but it should return 404.

I haven't done any investigating, but didn't see this on the issues list.

**Comment by ashleygwilliams** [comment]
hi @kardeiz ! my understanding of the example is that `/hello` returns `<h1>Hi!</h1><p>Hello Rust!</p>` and that `/` returns the 404. it seems to be behaving as such, do you think you explain why you expect other behavior?

**Comment by kardeiz** [comment]
The example also matches on the request method, and the `Hi!` arm should match only requests with `Method::GET`. My `curl` request should not match this arm since the request method is (or should be) `Method::POST`.

**Comment by ashleygwilliams** [comment]
ah ha! i missed that when i initially read your issue. good catch! we should be sure that the method is being figured in. thanks for the file!

**Comment by steveklabnik** [comment]
I had suspicions that we weren't handling methods correctly, but wasn't sure. Thanks for the report!

**Comment by steveklabnik** [comment]
This has now been fixed!

```bash
> Invoke-WebRequest -Uri http://localhost:7878/hello -Method POST
Invoke-WebRequest : 404
Not found!
At line:1 char:1
+ Invoke-WebRequest -Uri http://localhost:7878/hello -Method POST
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
