### ISSUE TITLE
README has 0.1.0

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/simple-server#87]
it should have the current version.

**Comment by sunjay** [comment]
We ran into this at RustBridge Waterloo today. Took a while to figure out that we had the wrong version. Would be great if a new fixed version could be published for future people. :smile:

**Comment by steveklabnik** [comment]
Oh no!

I'm planning on cutting a release on Monday or Tuesday, so will fix it up for sure.

**Comment by sunjay** [comment]
Thank you! 

This is a great crate! We had so much fun with it today. A particularly excited participant managed to start opening and serving files before we had even finished the first part of the compliments app. Awesome job!

**Comment by steveklabnik** [comment]
Okay so, turns out this is already fixed on master. crates.io is rendering an old readme.

so this will just be fixed with the next release!

**Comment by sunjay** [comment]
Hi @steveklabnik! The README on crates.io is still outdated. We ran into this today in RustBridge. Would be awesome to get a release (even a patch release if the actual one is still far off).:)

**Comment by steveklabnik** [comment]
Oh no!

Yeah I gotta cut one... sorry :(
