### ISSUE TITLE
Since Server::listen blocks forever should it be marked diverging?

### ISSUE THREAD

**Issue by cpick** [steveklabnik/simple-server#95]
The [`Server::listen`](https://docs.rs/simple-server/0.3.0/simple_server/struct.Server.html#method.listen) docs say that it blocks forever I believe that implies that it's a [diverging function](https://doc.rust-lang.org/nightly/book/first-edition/functions.html#diverging-functions) so it's return type should indicate that, right?

Ie:
````rust
pub fn listen(&self, host: &str, port: &str) -> ! {...}
````
Instead of the current:
````rust
pub fn listen(&self, host: &str, port: &str) {...}
````

This would allow the compiler to more correctly reason about code paths around calls to `listen`.

**Comment by steveklabnik** [comment]
Seems good!
